spring:
  docker:
    compose:
      enabled: true
  batch:
    job:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  modulith:
    events:
      republish-outstanding-events-on-restart: true
logging:
  level:
    com.ok: INFO
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
