server:
  port: 8080
spring:
  application:
    name: paldo-gotgan
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: dev
  jackson:
    time-zone: ${APP_TIME_ZONE:UTC}
    serialization:
      fail-on-empty-beans: false
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/paldogotgan?serverTimezone=${APP_TIME_ZONE:UTC}&characterEncoding=UTF-8}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 100
          time_zone: ${APP_TIME_ZONE:UTC}
app:
  problem:
    base-uri: ${PROBLEM_BASE_URI:about:blank}
  s3:
    region: ${AWS_REGION}
    bucket: ${S3_BUCKET}
