-- 배송 (판매자별 송장 단위)
CREATE TABLE shipment (
    id                       BIGINT       NOT NULL AUTO_INCREMENT,
    order_id                 BIGINT       NOT NULL COMMENT '주문 ID',
    seller_id                BIGINT       NOT NULL COMMENT '판매자 ID',
    status                   VARCHAR(20)  NOT NULL COMMENT 'ShipmentStatus',
    carrier                  VARCHAR(30)  NULL     COMMENT '택배사 코드, 송장 등록 전 null',
    tracking_number          VARCHAR(13)  NULL     COMMENT '송장번호, 송장 등록 전 null',
    recipient_name           VARCHAR(50)  NOT NULL COMMENT '현재 배송지 - 수령인',
    recipient_phone          VARCHAR(11)  NOT NULL COMMENT '현재 배송지 - 연락처 (숫자만)',
    postal_code              VARCHAR(5)   NOT NULL COMMENT '현재 배송지 - 우편번호',
    address                  VARCHAR(255) NOT NULL COMMENT '현재 배송지 - 주소',
    address_detail           VARCHAR(255) NOT NULL COMMENT '현재 배송지 - 상세 주소',
    delivery_note            VARCHAR(255) NULL     COMMENT '현재 배송지 - 배송 요청사항',
    region_group             VARCHAR(30)  NOT NULL COMMENT '지역 그룹 코드',
    base_shipping_fee        INT          NOT NULL COMMENT '기본 배송비 (결제 시점)',
    region_surcharge         INT          NOT NULL COMMENT '추가 운임 (결제 시점)',
    free_shipping_threshold  INT          NOT NULL COMMENT '무료배송 기준 금액 (결제 시점)',
    estimated_delivery_start DATE         NOT NULL COMMENT '도착 예정일 시작',
    estimated_delivery_end   DATE         NOT NULL COMMENT '도착 예정일 끝',
    is_delayed               BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '지연 여부 (DELAYED는 예약어)',
    shipped_at               DATETIME(6)  NULL,
    delivered_at             DATETIME(6)  NULL,
    completed_at             DATETIME(6)  NULL,
    cancelled_at             DATETIME(6)  NULL,
    created_at               DATETIME(6)  NOT NULL,
    updated_at               DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_shipment_tracking_number UNIQUE (tracking_number),
    CONSTRAINT uk_shipment_order_seller UNIQUE (order_id, seller_id),
    CONSTRAINT ck_shipment_fee CHECK (base_shipping_fee >= 0 AND region_surcharge >= 0 AND free_shipping_threshold >= 0),
    CONSTRAINT ck_shipment_estimated_delivery CHECK (estimated_delivery_start <= estimated_delivery_end)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 배송 상품 항목
CREATE TABLE shipment_item (
    id                BIGINT       NOT NULL AUTO_INCREMENT,
    shipment_id       BIGINT       NOT NULL,
    order_item_id     BIGINT       NOT NULL COMMENT '주문 상품 ID',
    product_name      VARCHAR(255) NOT NULL COMMENT '상품명 (결제 시점)',
    option_name       VARCHAR(255) NULL     COMMENT '옵션명 (결제 시점)',
    quantity          INT          NOT NULL COMMENT '수량',
    unit_price        INT          NOT NULL COMMENT '단가 (결제 시점)',
    canceled_quantity INT          NOT NULL DEFAULT 0 COMMENT '취소 확정 수량',
    confirmed         BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '구매확정 여부',
    created_at        DATETIME(6)  NOT NULL,
    updated_at        DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_shipment_item_order_item_id UNIQUE (order_item_id),
    CONSTRAINT fk_shipment_item_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT ck_shipment_item_quantity CHECK (quantity > 0 AND canceled_quantity >= 0 AND canceled_quantity <= quantity),
    CONSTRAINT ck_shipment_item_unit_price CHECK (unit_price >= 0)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 배송지 변경 요청 (요청 한 건이 한 행, 변경 전·후 배송지를 이력으로 남긴다)
CREATE TABLE shipment_address_change_request (
    id                        BIGINT       NOT NULL AUTO_INCREMENT,
    shipment_id               BIGINT       NOT NULL,
    requested_recipient_name  VARCHAR(50)  NOT NULL COMMENT '요청 배송지 - 수령인',
    requested_recipient_phone VARCHAR(11)  NOT NULL COMMENT '요청 배송지 - 연락처 (숫자만)',
    requested_postal_code     VARCHAR(5)   NOT NULL COMMENT '요청 배송지 - 우편번호',
    requested_address         VARCHAR(255) NOT NULL COMMENT '요청 배송지 - 주소',
    requested_address_detail  VARCHAR(255) NOT NULL COMMENT '요청 배송지 - 상세 주소',
    requested_delivery_note   VARCHAR(255) NULL     COMMENT '요청 배송지 - 배송 요청사항',
    previous_recipient_name   VARCHAR(50)  NOT NULL COMMENT '변경 전 배송지 - 수령인',
    previous_recipient_phone  VARCHAR(11)  NOT NULL COMMENT '변경 전 배송지 - 연락처 (숫자만)',
    previous_postal_code      VARCHAR(5)   NOT NULL COMMENT '변경 전 배송지 - 우편번호',
    previous_address          VARCHAR(255) NOT NULL COMMENT '변경 전 배송지 - 주소',
    previous_address_detail   VARCHAR(255) NOT NULL COMMENT '변경 전 배송지 - 상세 주소',
    previous_delivery_note    VARCHAR(255) NULL     COMMENT '변경 전 배송지 - 배송 요청사항',
    status                    VARCHAR(20)  NOT NULL COMMENT 'AddressChangeStatus',
    additional_fee_notice     INT          NOT NULL DEFAULT 0 COMMENT '추가 운임 안내 금액',
    reject_reason             VARCHAR(255) NULL     COMMENT '거절 사유',
    requested_at              DATETIME(6)  NOT NULL,
    processed_at              DATETIME(6)  NULL,
    created_at                DATETIME(6)  NOT NULL,
    updated_at                DATETIME(6)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_sacr_shipment_id FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT ck_sacr_additional_fee_notice CHECK (additional_fee_notice >= 0)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
